---
- name: Download Collections in tmp folder
  ansible.builtin.shell: ansible-galaxy install RedHatOfficial.rhel8_stig

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - RedHatOfficial.rhel8_stig
