---
- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  tasks:
    - name: Installion of Collection
      command: ansible-galaxy install RedHatOfficial.rhel8_stig
  roles:
    - RedHatOfficial.rhel8_stig
