---
collections:
  # Install a collection from Ansible Collections.
  - name: redhatofficial.rhel8_stig
    source: https://galaxy.ansible.com

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - RedHatOfficial.rhel8_stig
